{{- if .Values.trivy.externalRegoPoliciesEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trivy-operator.policiesConfigMapName" . }}
  namespace: {{ include "trivy-operator.namespace" . }}
  labels:
    {{- include "trivy-operator.labels" . | nindent 4 }}
data:
  {{- .Values.trivyOperator.policiesConfig | nindent 2 }}
{{- end }}